### ISSUE TITLE
GithubDB is not a constructor

### ISSUE THREAD

**Issue by prepper25** [usmakestwo/githubDB#10]
i'm getting this error  var githubDB = new GithubDB(options);
TypeError: GithubDB is not a constructor

**Comment by gonzalovazquez** [comment]
Hey @prepper25 , how are you importing the module? 

I would recommend importing with this: 

`var GithubDB = require('githubdb').default;`

**Comment by gonzalovazquez** [comment]
Closing as no more help is required.
