### ISSUE TITLE
Have the ability pass the Github host name during configuration

### ISSUE THREAD

**Issue by gonzalovazquez** [usmakestwo/githubDB#2]
https://github.com/usmakestwo/githubDB/blob/master/lib/githubdb.js#L34

**Comment by DineshAlapati** [comment]
@gonzalovazquez, can you give access to push to this repo?

<img width="684" alt="screen shot 2017-09-22 at 4 59 03 pm" src="https://user-images.githubusercontent.com/7747333/30764081-63fbea02-9fb7-11e7-8742-d989d0f76f06.png">

**Comment by gonzalovazquez** [comment]
You can write/read access to the repo.

As well, you should have access to Travis now.

https://travis-ci.org/usmakestwo/githubDB

**Comment by DineshAlapati** [comment]
@gonzalovazquez, Still don't see **configure** option on Travis CI. I can't fix the build without this access.

<img width="1067" alt="screen shot 2017-09-23 at 1 09 26 pm" src="https://user-images.githubusercontent.com/7747333/30775392-7e1a6766-a060-11e7-88dc-19ccf916aa29.png">

**Comment by gonzalovazquez** [comment]
Okay try again, you are admin now of the repository.

**Comment by gonzalovazquez** [comment]
Build is passing now!

**Comment by gonzalovazquez** [comment]
github-db@1.1.1 has been published!
